# Generated by Django 3.2.7 on 2021-09-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='test',
            new_name='text',
        ),
    ]
